version: "3"

services:
  php:
    container_name: se-school-3_php
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
    working_dir: /se_school_3/
    volumes:
      - ./app:/se_school_3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  nginx:
    container_name: se-school-3_nginx
    image: nginx:latest
    restart: unless-stopped
    working_dir: /se_school_3/
    ports:
      - "8000:80"
    volumes:
      - ./docker/configs/nginx/conf.d:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
      - ./app:/se_school_3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
